Regra viagens sem transação
prefeitura-rio/pipelines_rj_smtr pull request #121
Opened 2024-07-24 21:13 UTC by akaBotelho

2024-08-01 14:14 UTC, eng-rodrigocunha requested changes

2024-08-01 14:14 UTC, eng-rodrigocunha commented on queries/dbt_project.yml
> +      +schema: subsidio
Inserir:
- materialized="incremental",
- incremental_strategy="insert_overwrite"

2024-08-01 14:14 UTC, eng-rodrigocunha commented on queries/models/subsidio/schema.yml
> +        description: "Código único identificador da viagem."
Inserir no docs

2024-08-01 14:14 UTC, eng-rodrigocunha commented on queries/models/subsidio/schema.yml
> +        description: "Serviço realizado pelo veículo."
Inserir no docs

2024-08-01 14:14 UTC, eng-rodrigocunha commented on queries/models/subsidio/schema.yml
> +        description: "Classificação do tipo de viagem."
Inserir no docs

2024-08-01 14:14 UTC, eng-rodrigocunha commented on queries/models/subsidio/schema.yml
> +        description: "Quantidade de transações da Jaé durante a viagem."
Inserir descrição do período considerado

2024-08-01 14:14 UTC, eng-rodrigocunha commented on queries/models/subsidio/schema.yml
> +        description: "Quantidade de transações da RioCard durante a viagem."
Inserir descrição do período considerado

2024-08-01 14:14 UTC, eng-rodrigocunha commented on queries/models/subsidio/schema.yml
> +        description: "Indicador se todos os registros de GPS foram transmitidos com o estado ABERTO durante a viagem."
Inserir descrição do período considerado

2024-08-01 14:14 UTC, eng-rodrigocunha commented on queries/models/subsidio/schema.yml
> +        description: "Horário de início da viagem para contagem das transações, considerando uma tolerância de até 30 minutos do ínicio da viagem, limitada pelo encerramento da viagem anterior realiz
+1 segundo

2024-08-01 14:14 UTC, eng-rodrigocunha commented on queries/models/subsidio/viagem_transacao.sql
> +        ), INTERVAL 1 SECOND))
Não seria `TIMESTAMP_ADD`?

2024-08-01 14:14 UTC, eng-rodrigocunha commented on queries/models/subsidio/viagem_transacao.sql
> +-- ),
Remover comentários desnecessários (?)

2024-08-01 14:14 UTC, eng-rodrigocunha commented on queries/models/subsidio/viagem_transacao.sql
> +-- ),
Fazer só quando formos subir para prod

2024-08-01 14:14 UTC, eng-rodrigocunha commented on queries/models/subsidio/viagem_transacao.sql
> +    --     OR eev.conta_estado_fechado != 0)
Remover comentários desnecessários

2024-08-01 14:14 UTC, eng-rodrigocunha commented
@akaBotelho na descrição do PR, adiciona todos os changelogs

2024-08-01 14:15 UTC, eng-rodrigocunha commented
@akaBotelho quando fechar para revisão, pode retirar o `[WIP]` do título

2024-08-01 14:32 UTC, akaBotelho commented on queries/dbt_project.yml
> +      +schema: subsidio
Alterado

2024-08-01 14:40 UTC, akaBotelho commented on queries/models/subsidio/schema.yml
> +        description: "Horário de início da viagem para contagem das transações, considerando uma tolerância de até 30 minutos do ínicio da viagem, limitada pelo encerramento da viagem anterior realiz
Alterado

2024-08-01 14:41 UTC, akaBotelho commented on queries/models/subsidio/schema.yml
> +        description: "Quantidade de transações da Jaé durante a viagem."
Alterado

2024-08-01 14:41 UTC, akaBotelho commented on queries/models/subsidio/schema.yml
> +        description: "Quantidade de transações da RioCard durante a viagem."
Alterado

2024-08-01 14:42 UTC, akaBotelho commented on queries/models/subsidio/schema.yml
> +        description: "Indicador se todos os registros de GPS foram transmitidos com o estado ABERTO durante a viagem."
Alterado

2024-08-01 14:46 UTC, akaBotelho commented on queries/models/subsidio/schema.yml
> +        description: "Classificação do tipo de viagem."
Alterado

2024-08-01 14:46 UTC, akaBotelho commented on queries/models/subsidio/schema.yml
> +        description: "Serviço realizado pelo veículo."
Alterado

2024-08-01 14:46 UTC, akaBotelho commented on queries/models/subsidio/schema.yml
> +        description: "Código único identificador da viagem."
Alterado

2024-08-01 14:49 UTC, akaBotelho commented on queries/models/subsidio/viagem_transacao.sql
> +    --     OR eev.conta_estado_fechado != 0)
Alterado

2024-08-01 14:50 UTC, akaBotelho commented on queries/models/subsidio/viagem_transacao.sql
> +        ), INTERVAL 1 SECOND))
usei DATETIME(TIMESTAMP_ADD antes do GREATEST

2024-08-07 20:29 UTC, eng-rodrigocunha approved these changes

2024-08-07 20:29 UTC, merged