Cria tabela de autuaçoes com dados da citran
prefeitura-rio/pipelines_rj_smtr pull request #184
Opened 2024-09-03 15:26 UTC by vtr363

2024-09-03 18:21 UTC, eng-rodrigocunha requested changes

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +    description: "Tabela de autuações fornecidas pela citran e serpro"
"Tabela com dados de autuações (até abril/2023)"

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +        description: "Data da autuação (Colunade particionamento)"
Coluna de

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +        - 'projects/rj-smtr/locations/us/taxonomies/7968932463054912793/policyTags/5243840798726507169'
Essa tag não é necessária neste campo. Corrigir descrição.

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +      - name: id_auto_infracao
Adicionar tag neste campo. Corrigir descrição.

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +        description: "Data limite para recurso"
`"Data limite para recurso em primeira instância"`

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +        description: "Data limite para recurso"
`"Data limite para recurso em primeira instância"`

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +        description: "Placa do veiculo"
Adicionar tag e corrigir acentuação

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +        description: "Estado do condutor infrator (em caso de indicação de real condutor)"
`"Estado do condutor infrator (em caso de indicação de real condutor infrator)"`

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +        description: "Valor monetário da autuação (100%)"
Indicar unidade monetária

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +        description: "Valor pago da autuação"
Indicar unidade monetária

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +        description: "Valor pago da autuação"
Indicar unidade monetária

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +        description: "Hexagono da autuação"
Corrigir acentuação

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +        description: "Numero do processo de defesa prévia"
Corrigir acentuação

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +        description: "Número do processo de recurso contra penalidade de multa em primeira instância"
`"Número do processo de recurso contra aplicação de penalidade de multa em primeira instância"`

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +        description: "Numero do processo de troca de real infrator"
`processo_troca_real_condutor_infrator`
`"Número do processo de troca de real condutor infrator"`

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/schema.yml
> +        description: "Indicador de adesão do veículo ao SNE"
`"Indicador de adesão do veículo ao Sistema de Notificação Eletrônica (SNE)"`

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/staging/autuacoes_citran.sql
> +  SAFE_CAST(JSON_VALUE(content,'$.VlPagto') AS NUMERIC) valor_pago,
Verificar separador de casas decimais ou dividir por 100 na outra tabela

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/autuacoes.sql
> +        processo_troca_real_infrator,
Para os campos `processo_defesa_autuacao`, `recurso_penalidade_multa` e `processo_troca_real_infrator`, caso seja uma string "" ou "00000000", transformar em NULL

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/autuacoes.sql
> +        uf_proprietario,
Caso seja uma string "", transformar em NULL

2024-09-03 18:21 UTC, eng-rodrigocunha commented on queries/models/infracao/autuacoes.sql
> +        tipo_veiculo,
Caso seja uma string "", transformar em NULL

2024-09-04 13:19 UTC, pixuimpou requested changes

2024-09-04 13:19 UTC, pixuimpou commented on queries/models/transito/autuacao.sql
> +    select
deixar select em maiúsculo

2024-09-04 13:27 UTC, pixuimpou submitted a review, later dismissed

2024-09-04 13:52 UTC, pixuimpou approved these changes

2024-09-04 13:53 UTC, merged