Adiciona os testes do subsidio no dbt
prefeitura-rio/pipelines_rj_smtr pull request #256
Opened 2024-10-02 20:45 UTC by vtr363

2024-10-25 12:14 UTC, eng-rodrigocunha commented on queries/macros/test_check_gps_treatment.sql
> +start_date{% test check_gps_treatment(model) -%}
Remover `start_date`

2024-10-25 12:15 UTC, eng-rodrigocunha commented on queries/macros/test_accepted_values_valor_penalidade.sql
> +{% test accepted_values_valor_penalidade(model) -%}
Faria sentido um modelo mais genérico? Todos os valores aceitos nesta coluna x de uma tabela precisam estar na coluna y de outra?

2024-10-25 12:16 UTC, eng-rodrigocunha commented on queries/macros/test_check_sppo_veiculo_dia.sql
> +{% test check_sppo_veiculo_dia(model) %}
Isso não poderia ser substituído por testes de unicidade e nulidade?

2024-10-25 12:17 UTC, eng-rodrigocunha commented on queries/macros/test_check_trips_processing.sql
> +start_date{% test check_trips_processing(model) -%}
Remover `start_date`

2024-10-25 12:17 UTC, eng-rodrigocunha commented on queries/macros/test_check_trips_processing.sql
> +        DATA >= "2024-04-01" -- DATA_SUBSIDIO_V6_INICIO (Feature trajetos alternativos)
Substituir data pela variável

2024-10-25 12:18 UTC, eng-rodrigocunha commented on queries/macros/test_check_viagem_completa.sql
> +{%- endtest %}
Substituir datas pelas variáveis

2024-10-25 12:19 UTC, eng-rodrigocunha commented on queries/macros/test_expression_is_true.sql
> +{% test expression_is_true(model, expression) -%}
Remover teste

2024-10-25 12:19 UTC, eng-rodrigocunha commented on queries/macros/test_subsido_viagens_atualizadas.sql
> +{%- endtest %}
Substituir datas pelas variáveis

2024-10-25 12:20 UTC, eng-rodrigocunha commented on queries/macros/test_teto_pagamento_valor_subsidio_pago.sql
> +        -- {{ ref('subsidio_valor_km_tipo_viagem') }}
Usar referência

2024-10-25 12:21 UTC, eng-rodrigocunha commented on queries/macros/test_unique_combination.sql
> +{% test unique_combination(model, expression) -%}
Remover teste

2024-10-25 12:26 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo_v2/schema.yml
> +              at_least: 1
Está certo isso?

2024-11-05 00:22 UTC, eng-rodrigocunha requested changes

2024-11-05 00:22 UTC, eng-rodrigocunha commented on queries/macros/custom_get_where_subquery.sql
> -            (select * from {{ relation }} where {{ where }}) dbt_subquery
Por quê?

2024-11-05 00:22 UTC, eng-rodrigocunha commented on queries/models/veiculo/schema.yml
> +      - check_sppo_veiculo_dia:
Esse teste é necessário? Não é o mesmo que o próximo?

2024-11-05 00:22 UTC, eng-rodrigocunha commented on queries/macros/test_check_sppo_veiculo_dia.sql
> +{% test check_sppo_veiculo_dia(model) %}
Esse teste é necessário?

2024-11-05 00:22 UTC, eng-rodrigocunha commented on queries/macros/test_check_trips_processing.sql
> +        rj-smtr.projeto_subsidio_sppo.subsidio_data_versao_efetiva
Atualiza ref

2024-11-05 00:22 UTC, eng-rodrigocunha commented on queries/macros/test_accepted_values_valor_penalidade.sql
> +{% test accepted_values_in_table(model, column_name, ref_table, ref_column) %}
Não deu certo usar uma subquery no teste genérico?

2024-11-05 00:22 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +          test_end_date: "{{ var('date_range_end') }}" # (Optional. Replace 'yyyy-mm-dd' with a date. Default is 'None')
Remover comentários. Variáveis funcionaram?

2024-11-05 00:22 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +          test_end_date: DATE("{{ var("end_date") }}") # (Optional. Replace 'yyyy-mm-dd' with a date. Default is 'None')
Remover comentários

2024-11-05 00:22 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +          test_end_date: "{{ var('date_range_end') }}" # (Optional. Replace 'yyyy-mm-dd' with a date. Default is 'None')
Remover comentários

2024-11-05 00:22 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo_v2/schema.yml
> +          test_end_date: "{{ var('date_range_end') }}" # (Optional. Replace 'yyyy-mm-dd' with a date. Default is 'None')
Remover comentários

2024-11-13 12:40 UTC, vtr363 commented on queries/macros/custom_get_where_subquery.sql
> -            (select * from {{ relation }} where {{ where }}) dbt_subquery
O `dbt_subquery` gerava um erro nos testes do dbt_expectations

2024-11-26 18:45 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +          name: completness__sumario_servico_dia
Ajustar nome

2024-11-26 18:45 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +          name: unique_combination__data_servico__sumario_servico_dia
Ajustar nome

2024-11-26 18:46 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__viagens__sumario_servico_dia
Ajustar nome

2024-11-26 18:46 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__km_apurada__sumario_servico_dia
Ajustar nome

2024-11-26 18:46 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__km_planejada__sumario_servico_dia
Ajustar nome

2024-11-26 18:46 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__perc_km_planejada__sumario_servico_dia
Ajustar nome

2024-11-26 18:46 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__valor_subsidio_pago__sumario_servico_dia
Ajustar nome

2024-11-26 18:47 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +          - accepted_values_in_table:
Há um outro teste genérico que possibilita substituir este. Verificar nos testes do GTFS.

2024-11-26 18:47 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +          name: completness__sumario_servico_dia_tipo_sem_glosa
Ajustar nome

2024-11-26 18:48 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +          name: unique_combination__data_servico__sumario_servico_dia_tipo_sem_glosa
Ajustar nome

2024-11-26 18:48 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__viagens_subsidio__sumario_servico_dia_tipo_sem_glosa
Ajustar nome

2024-11-26 18:48 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__distancia_total_planejada__sumario_servico_dia_tipo_sem_glosa
Ajustar nome

2024-11-26 18:48 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__distancia_total_planejada__sumario_servico_dia_tipo_sem_glosa
Ajustar nome

2024-11-26 18:48 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
>          description: "."
Ajustar descrição

2024-11-26 18:48 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__perc_distancia_total_subsidio__sumario_servico_dia_tipo_sem_glosa
Ajustar nome

2024-11-26 18:48 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__valor_total_subsidio__sumario_servico_dia_tipo_sem_glosa
Ajustar nome

2024-11-26 18:49 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__viagens_autuado_seguranca__sumario_servico_dia_tipo_sem_glosa
Ajustar nome

2024-11-26 18:49 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__km_apurada_autuado_seguranca__sumario_servico_dia_tipo_sem_glosa
Ajustar nome

2024-11-26 18:49 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__viagens_autuado_limpezaequipamento__sumario_servico_dia_tipo_sem_glosa
Ajustar nome

2024-11-26 18:49 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__km_apurada_autuado_limpezaequipamento__sumario_servico_dia_tipo_sem_glosa
Ajustar nome

2024-11-26 18:49 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__viagens_licenciado_sem_ar_n_autuado__sumario_servico_dia_tipo_sem_glosa
Ajustar nome

2024-11-26 18:49 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__km_apurada_licenciado_sem_ar_n_autuado__sumario_servico_dia_tipo_sem_glosa
Ajustar nome

2024-11-26 18:49 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__viagens_licenciado_com_ar_n_autuado__sumario_servico_dia_tipo_sem_glosa
Ajustar nome

2024-11-26 18:49 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +              name: greater_than_zero__km_apurada_licenciado_com_ar_n_autuado__sumario_servico_dia_tipo_sem_glosa
Ajustar nome

2024-11-26 18:50 UTC, eng-rodrigocunha commented on queries/models/dashboard_subsidio_sppo/schema.yml
> +          name: viagem_completa__viagens_remuneradas
Ajustar nome

2024-11-26 18:50 UTC, eng-rodrigocunha commented on queries/profiles.yml
>        dataset: dbt
Remover essas alterações

2024-11-29 19:43 UTC, eng-rodrigocunha approved these changes

2024-12-17 17:24 UTC, akaBotelho approved these changes

2024-12-17 17:33 UTC, akaBotelho submitted a review, later dismissed

2024-12-18 14:27 UTC, akaBotelho approved these changes

2024-12-18 15:39 UTC, merged