Parâmetro de invalidação por velocidade maior 200 km/h
prefeitura-rio/pipelines_rj_smtr pull request #340
Opened 2024-11-27 14:52 UTC by akaBotelho

2024-11-27 15:04 UTC, eng-rodrigocunha requested changes

2024-11-27 15:04 UTC, eng-rodrigocunha commented on queries/models/projeto_subsidio_sppo/viagem_completa.sql
> +    velocidade_media < {{ var("conformidade_velocidade") }} or ST_DISTANCE(s.start_pt, s.end_pt) between 1900 and 1950
- Aplicar apenas apenas após `2024-11-16` (inserir data como variável)
- Não faria mais sentido algo como `velocidade_media < {{ var("conformidade_velocidade") }} and ST_DISTANCE(s.start_pt, s.end_pt) > 1900`?

2024-11-27 15:04 UTC, eng-rodrigocunha commented on queries/dbt_project.yml
> +  conformidade_velocidade: 200
`conformidade_velocidade_min`

2024-11-27 15:04 UTC, eng-rodrigocunha commented on queries/models/projeto_subsidio_sppo/CHANGELOG.md
> +- Adiciona filtro para remover as viagens com velocidade superior a 200km/h, exceto os serviços 013 e 851 no modelo `viagem_completa.sql` (https://github.com/prefeitura-rio/pipelines_rj_smtr/pull/340
Sugestão de texto (avaliar): "exceto os serviços com distância linear entre o início e final inferior a 1900 m (ex: 013 e 851)"

2024-11-27 15:08 UTC, eng-rodrigocunha requested changes

2024-11-27 15:08 UTC, eng-rodrigocunha commented on queries/models/projeto_subsidio_sppo/viagem_conformidade.sql
>      round(100 * n_registros_minuto/tempo_viagem, 2) as perc_conformidade_registros,
Incluir `CURRENT_DATETIME("America/Sao_Paulo") as datetime_ultima_atualizacao`

2024-11-29 18:19 UTC, eng-rodrigocunha requested changes

2024-11-29 18:19 UTC, eng-rodrigocunha commented on queries/models/projeto_subsidio_sppo/CHANGELOG.md
> +- Adiciona filtro para remover as viagens com velocidade superior a 200km/h, exceto os serviços com distância linear entre o início e o final inferior a 2000m e que possuem interseção entre o trajeto
```suggestion
- Adiciona filtro para remover as viagens com velocidade média superior a 200km/h, exceto os serviços que atendam a um dos seguintes critérios:
   - Distância linear entre o ponto de início e final inferior a 2000m;
   - Possuam mais de um ponto de interseção entre o trajeto e os buffers (atualmente 500 m) gerados a partir dos pontos de início ou final do trajeto;
   - Sejam circulares.
   (https://github.com/prefeitura-rio/pipelines_rj_smtr/pull/340)
```

2024-12-09 19:30 UTC, eng-rodrigocunha requested changes

2024-12-09 19:30 UTC, eng-rodrigocunha commented on queries/models/projeto_subsidio_sppo/viagem_completa.sql
> +  velocidade_media < {{ var("conformidade_velocidade_min") }} or (((ST_NUMGEOMETRIES(ST_INTERSECTION(ST_BUFFER(start_pt, 500), shape)) > 1 or ST_NUMGEOMETRIES(ST_INTERSECTION(ST_BUFFER(end_pt, 500),
Alterar 500 para variável

2024-12-09 19:30 UTC, eng-rodrigocunha commented on queries/models/projeto_subsidio_sppo/viagem_completa.sql
> +  and ST_DISTANCE(start_pt, end_pt) < 2000) and sentido != "C")
Alterar 2000 para variável

2024-12-13 13:11 UTC, akaBotelho commented on queries/models/projeto_subsidio_sppo/viagem_conformidade.sql
Adicionar datetime_ultima_atualizacao

2024-12-13 17:15 UTC, vtr363 approved these changes

2024-12-13 17:23 UTC, eng-rodrigocunha approved these changes

2024-12-13 17:23 UTC, merged