Migração - br_rj_riodejaneiro_onibus_gps_zirix
prefeitura-rio/pipelines_rj_smtr pull request #67
Opened 2024-06-19 14:02 UTC by akaBotelho

2024-06-19 18:15 UTC, pixuimpou requested changes

2024-06-19 18:15 UTC, pixuimpou commented on pipelines/br_rj_riodejaneiro_onibus_gps_zirix/flows.py
> +                project_name=smtr_constants.PREFECT_DEFAULT_PROJECT.value,
Alterar essa linha para pegar o nome do projeto atual do flow. usando a task get_flow_project. Tem um exemplo disso no pipeline do onibus_gps neste repo

2024-06-19 18:15 UTC, pixuimpou commented on pipelines/br_rj_riodejaneiro_onibus_gps_zirix/flows.py
> +                project_name=smtr_constants.PREFECT_DEFAULT_PROJECT.value,
Alterar essa linha para pegar o nome do projeto atual do flow. usando a task get_flow_project. Tem um exemplo disso no pipeline do onibus_gps neste repo

2024-06-19 19:04 UTC, akaBotelho commented on pipelines/br_rj_riodejaneiro_onibus_gps_zirix/flows.py
> +                project_name=smtr_constants.PREFECT_DEFAULT_PROJECT.value,
Alterado

2024-06-19 19:04 UTC, akaBotelho commented on pipelines/br_rj_riodejaneiro_onibus_gps_zirix/flows.py
> +                project_name=smtr_constants.PREFECT_DEFAULT_PROJECT.value,
Alterado

2024-06-20 13:45 UTC, pixuimpou approved these changes

2024-06-20 14:38 UTC, merged